import { Outfit } from "next/font/google";
import "src/styles/main.scss";

const outfit = Outfit({
  subsets: ["latin"],
  weight: ["400", "700"], // load regular + bold
  variable: "--font-outfit", // custom CSS variable
});

export const metadata = {
  title: "QR Code",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={outfit.variable}>
      <body>{children}</body>
    </html>
  );
}
